---
#
# Internal variable mapping
# Edit config.yml for project settings.
#
jenkins_deploy_mode: "{{ global_deploy_mode }}"
sonarqube_deploy_mode: "{{ global_deploy_mode }}"
jenkins_enable_tls: "{{ enable_tls }}"
sonarqube_enable_tls: "{{ enable_tls }}"
jenkins_tls_email: "{{ tls_email }}"
sonarqube_tls_email: "{{ tls_email }}"
jenkins_ingress_class_name: "{{ ingress_class_name }}"
sonarqube_ingress_class_name: "{{ ingress_class_name }}"
jenkins_kubeconfig_path: "{{ k8s_kubeconfig_path }}"
sonarqube_kubeconfig_path: "{{ k8s_kubeconfig_path }}"
