---
galaxy_info:
  role_name: sonarqube
  author: alexkgm
  description: Deploy SonarQube and PostgreSQL with Docker Compose or Kubernetes.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - sonarqube
    - postgresql
    - docker
    - kubernetes
dependencies: []
