---
- name: Prepare SonarQube Docker directories
  ansible.builtin.include_tasks: docker_install.yml

- name: Deploy SonarQube Docker Compose stack
  ansible.builtin.include_tasks: docker_deploy.yml

- name: Configure Nginx for SonarQube
  ansible.builtin.include_tasks: nginx.yml

- name: Configure TLS for SonarQube
  ansible.builtin.include_tasks: tls.yml
  when: sonarqube_enable_tls | bool
