---
- name: Install SonarQube base packages
  ansible.builtin.apt:
    name: "{{ sonarqube_base_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Apply SonarQube sysctl settings
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop: "{{ sonarqube_sysctl_settings }}"
  when: sonarqube_deploy_mode == "docker"
