---
- name: Install SonarQube base packages
  ansible.builtin.include_tasks: prereq_install.yml
  when: sonarqube_manage_base_packages | bool

- name: Install SonarQube Docker prerequisites
  ansible.builtin.include_tasks: prereq_docker.yml
  when: sonarqube_install_docker | bool

- name: Install SonarQube Nginx prerequisites
  ansible.builtin.include_tasks: prereq_nginx.yml
  when: sonarqube_install_nginx | bool

- name: Install SonarQube Certbot prerequisites
  ansible.builtin.include_tasks: prereq_certbot.yml
  when: sonarqube_install_certbot | bool

- name: Install SonarQube kubectl prerequisites
  ansible.builtin.include_tasks: prereq_kubectl.yml
  when: sonarqube_install_kubectl | bool
