---
- name: Add Kubernetes repository signing key for SonarQube role
  ansible.builtin.apt_key:
    url: "{{ sonarqube_kubectl_apt_key_url }}"
    state: present

- name: Add Kubernetes apt repository for SonarQube role
  ansible.builtin.apt_repository:
    repo: "{{ sonarqube_kubectl_apt_repo }}"
    filename: kubernetes
    state: present

- name: Install kubectl packages for SonarQube role
  ansible.builtin.apt:
    name: "{{ sonarqube_kubectl_packages }}"
    state: present
    update_cache: true

- name: Install Python packages required by kubernetes.core for SonarQube role
  ansible.builtin.pip:
    name: "{{ sonarqube_kubectl_python_packages }}"
    executable: pip3
    state: present
    extra_args: --upgrade
