---
install_docker: false
install_nginx: false
install_certbot: false
install_kubectl: false

common_base_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - git
  - gnupg
  - lsb-release
  - python3
  - python3-apt
  - python3-pip
  - python3-setuptools
  - software-properties-common
  - unzip

common_sysctl_settings:
  - name: vm.max_map_count
    value: "262144"
  - name: fs.file-max
    value: "65536"

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - python3-docker
docker_conflicting_packages:
  - docker.io
  - docker-compose
  - docker-compose-v2
  - docker-doc
  - podman-docker
  - containerd
  - runc
docker_remove_conflicting_packages: true
docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_apt_keyring_dir: /etc/apt/keyrings
docker_apt_key_path: "{{ docker_apt_keyring_dir }}/docker.asc"
docker_apt_repo_filename: docker
docker_apt_repo: >-
  deb [signed-by={{ docker_apt_key_path }}]
  https://download.docker.com/linux/ubuntu
  {{ ansible_facts['distribution_release'] | lower }}
  stable

nginx_packages:
  - nginx

certbot_packages:
  - certbot
  - python3-certbot-nginx

kubectl_apt_key_url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
kubectl_apt_repo: deb https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
kubectl_packages:
  - kubectl
  - python3-kubernetes
