# Keep this file simple.
# Change target hosts in config.yaml.
[bootstrap]
localhost ansible_connection=local

[common_targets]

[jenkins_targets]

[sonarqube_targets]

[harbor_targets]

[vault_targets]

[minio_targets]
