---
- name: Validate Jenkins configuration
  ansible.builtin.include_tasks: validate.yml

- name: Prepare Jenkins host prerequisites
  ansible.builtin.include_tasks: prerequisites.yml
  when: jenkins_manage_system_prereqs | bool

- name: Deploy Jenkins in Docker mode
  ansible.builtin.include_tasks: docker.yml
  when: jenkins_deploy_mode == "docker"

- name: Deploy Jenkins in Kubernetes mode
  ansible.builtin.include_tasks: k8s.yml
  when: jenkins_deploy_mode == "k8s"
