---
- name: Install Jenkins base packages
  ansible.builtin.include_tasks: prereq_install.yaml
  when: jenkins_manage_base_packages | bool

- name: Install Jenkins Docker prerequisites
  ansible.builtin.include_tasks: prereq_docker.yaml
  when: jenkins_install_docker | bool

- name: Install Jenkins Nginx prerequisites
  ansible.builtin.include_tasks: prereq_nginx.yaml
  when: jenkins_install_nginx | bool

- name: Install Jenkins Certbot prerequisites
  ansible.builtin.include_tasks: prereq_certbot.yaml
  when: jenkins_install_certbot | bool

- name: Install Jenkins kubectl prerequisites
  ansible.builtin.include_tasks: prereq_kubectl.yaml
  when: jenkins_install_kubectl | bool
