---
- name: Install Jenkins base packages
  ansible.builtin.include_tasks: prereq_install.yml
  when: jenkins_manage_base_packages | bool

- name: Install Jenkins Docker prerequisites
  ansible.builtin.include_tasks: prereq_docker.yml
  when: jenkins_install_docker | bool

- name: Install Jenkins Nginx prerequisites
  ansible.builtin.include_tasks: prereq_nginx.yml
  when: jenkins_install_nginx | bool

- name: Install Jenkins Certbot prerequisites
  ansible.builtin.include_tasks: prereq_certbot.yml
  when: jenkins_install_certbot | bool

- name: Install Jenkins kubectl prerequisites
  ansible.builtin.include_tasks: prereq_kubectl.yml
  when: jenkins_install_kubectl | bool
