---
- name: Remove Vault Helm release
  kubernetes.core.helm:
    kubeconfig: "{{ vault_kubeconfig_path }}"
    release_namespace: "{{ vault_namespace }}"
    name: "{{ vault_release_name }}"
    state: absent
  failed_when: false

- name: Remove Vault TLS secret
  kubernetes.core.k8s:
    kubeconfig: "{{ vault_kubeconfig_path }}"
    validate_certs: "{{ vault_k8s_validate_certs }}"
    state: absent
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ vault_k8s_ingress_tls_secret_name }}"
        namespace: "{{ vault_namespace }}"
  failed_when: false

- name: Remove Vault namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ vault_kubeconfig_path }}"
    validate_certs: "{{ vault_k8s_validate_certs }}"
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ vault_namespace }}"
  when: vault_cleanup_remove_namespace | bool
  failed_when: false
