---
- name: Remove Helm packages
  ansible.builtin.apt:
    name: "{{ helm_packages }}"
    state: absent
    purge: true
    autoremove: true

- name: Remove Helm apt repository
  ansible.builtin.apt_repository:
    repo: "{{ helm_apt_repo }}"
    filename: "{{ helm_apt_repo_filename }}"
    state: absent
    update_cache: true

- name: Remove Helm apt key
  ansible.builtin.file:
    path: "{{ helm_apt_key_path }}"
    state: absent
