---
- name: Add Kubernetes repository signing key
  ansible.builtin.apt_key:
    url: "{{ kubectl_apt_key_url }}"
    state: present

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "{{ kubectl_apt_repo }}"
    filename: kubernetes
    state: present

- name: Install kubectl packages
  ansible.builtin.apt:
    name: "{{ kubectl_packages }}"
    state: present
    update_cache: true
