---
- name: Install common packages and system settings
  ansible.builtin.include_tasks: install.yml

- name: Install Docker runtime
  ansible.builtin.include_tasks: docker.yml
  when: install_docker | bool

- name: Install Nginx
  ansible.builtin.include_tasks: nginx.yml
  when: install_nginx | bool

- name: Install Certbot
  ansible.builtin.include_tasks: certbot.yml
  when: install_certbot | bool

- name: Install kubectl
  ansible.builtin.include_tasks: kubectl.yml
  when: install_kubectl | bool
