---
- name: Deploy Traefik Proxy
  ansible.builtin.include_tasks: deploy.yaml
  when: deployment_state != "absent"

- name: Destroy Traefik Proxy
  ansible.builtin.include_tasks: destroy.yaml
  when: deployment_state == "absent"
