---
- name: Create Harbor namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ harbor_kubeconfig_path }}"
    validate_certs: "{{ harbor_k8s_validate_certs }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ harbor_namespace }}"
